## Pytorch : XOR Problem

### 1. XOR Dataset

In [1]:
import torch
import torch.nn as nn

device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [2]:
X = torch.FloatTensor([[0, 0],
                      [0, 1],
                      [1, 0],
                      [1, 1]]).to(device)

y = torch.FloatTensor([[0],
                       [1],
                       [1],
                       [0]]).to(device)

In [3]:
X.shape

torch.Size([4, 2])

In [4]:
y.shape

torch.Size([4, 1])

### 2. Perceptron 학습

In [14]:
linear = nn.Linear(2, 1, bias=True) # input 2개, output 1개
sigmoid = nn.Sigmoid()
model = nn.Sequential(linear, sigmoid)

In [15]:
criterion = torch.nn.BCELoss().to(device) # binary cross entropy 손실함수
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [16]:
for epoch in range(10000):
    y_pred = model(X)
    loss = criterion(y_pred, y)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if epoch % 1000 == 0:
        print(epoch, loss.item())

0 0.823107898235321
1000 0.6931472420692444
2000 0.6931471824645996
3000 0.6931471824645996
4000 0.6931471824645996
5000 0.6931471824645996
6000 0.6931471824645996
7000 0.6931471824645996
8000 0.6931471824645996
9000 0.6931471824645996


In [17]:
# prediction
with torch.no_grad():
    y_hat = (y_pred > 0.5).float()
    accuracy = (y_hat == y).float().mean()
    print(accuracy.item())

0.5


In [18]:
y_hat.detach()

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [19]:
y.detach()

tensor([[0.],
        [1.],
        [1.],
        [0.]])

결과가 제대로 안나오는 것을 볼 수 있다 -> 멀티레이어

### Multi-layered perceptron 해결

In [20]:
model = nn.Sequential(
    nn.Linear(2, 8, bias=True), # input layer
    nn.Sigmoid(),
    nn.Linear(8, 16, bias=True), # hidden layer
    nn.Sigmoid(),
    nn.Linear(16, 16, bias=True), # hidden layer
    nn.Sigmoid(),
    nn.Linear(16, 1, bias=True),  # hidden layer
    nn.Sigmoid()).to(device)  # output layer 

In [21]:
criterion = torch.nn.BCELoss().to(device) # binary cross entropy 손실함수
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [22]:
for epoch in range(10000):
    y_pred = model(X)
    loss = criterion(y_pred, y)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if epoch % 1000 == 0:
        print(epoch, loss.item())

0 0.6964862942695618
1000 0.6931489706039429
2000 0.693148136138916
3000 0.6931473612785339
4000 0.6931464672088623
5000 0.6931456923484802
6000 0.6931448578834534
7000 0.6931439638137817
8000 0.6931430697441101
9000 0.6931421160697937


In [23]:
# prediction
with torch.no_grad():
    y_hat = (y_pred > 0.5).float()
    accuracy = (y_hat == y).float().mean()
    print(accuracy.item())

0.5


In [24]:
y_hat.detach()

tensor([[1.],
        [0.],
        [1.],
        [0.]])